apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - loki-bucket-secret-externalsecret.yaml
helmCharts:
- name: loki
  namespace: logging
  includeCRDs: false
  releaseName: logging
  version: 6.29.0
  repo: https://grafana.github.io/helm-charts
  valuesInline:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: 2024-04-01
            object_store: s3
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage:
        type: 's3'
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
        s3:
          s3: null
          s3ForcePathStyle: true
          insecure: true
          endpoint: http://minio.minio.svc.cluster.local:9000
          accessKeyId: loki-svcacct
          secretAccessKey: ${S3_LOKI_SECRET_ACCESS_KEY}
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: S3_LOKI_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-bucket-secret
              key: loki-bucket-secret
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
- name: promtail
  namespace: logging
  includeCRDs: false
  releaseName: logging
  version: 6.16.6
  repo: https://grafana.github.io/helm-charts
  valuesInline:
    config:
      clients:
        - url: http://logging-loki-gateway/loki/api/v1/push