apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-bucket-secret
  namespace: logging
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: minio-user-secret-keys
        metadataPolicy: None
        property: loki-svcacct-secret-key
      secretKey: loki-bucket-secret