---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-bridge-token
  namespace: gotify
spec:
  refreshInterval: 24h
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: gotify-bridge-token
        metadataPolicy: None
        nullBytePolicy: Ignore
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-rk8s
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
