{{- if eq .Values.env "internal" }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: chap-secret
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    template:
      type: kubernetes.io/iscsi-chap
  data:
    - secretKey: node.session.auth.username
      remoteRef:
        key: prometheus-iscsi-chap
        property: username
    - secretKey: node.session.auth.password
      remoteRef:
        key: prometheus-iscsi-chap
        property: password
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-iscsi-pv
  labels:
    app.kubernetes.io/name: prometheus
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.2.5:3260
    iqn: iqn.2000-01.com.synology:igounas.prometheus.220186445f7
    lun: 1
    fsType: ext4
    readOnly: false
    secretRef:
      name: chap-secret
      namespace: monitoring
    chapAuthDiscovery: true
    chapAuthSession: true
...
{{- end }}
