apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-user-secret-keys
        property: admin-access-key
    - secretKey: rootPassword
      remoteRef:
        key: minio-user-secret-keys
        property: admin-secret-key
