apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-users
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: minio-user-secret-keys
