---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chap-secret
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    template:
      type: kubernetes.io/iscsi-chap
  data:
    - secretKey: node.session.auth.username
      remoteRef:
        key: minio-iscsi-chap
        property: username
    - secretKey: node.session.auth.password
      remoteRef:
        key: minio-iscsi-chap
        property: password
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-iscsi-pv
  labels:
    app.kubernetes.io/name: minio
spec:
  storageClassName: "minio"
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.10.9.224:3260
    iqn: iqn.2000-01.com.synology:igounas.minio.220186445f7
    lun: 1
    fsType: ext4
    readOnly: false
    secretRef:
      name: chap-secret
      namespace: minio
    chapAuthDiscovery: true
    chapAuthSession: true
...