---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: firecrawl-secrets
  namespace: firecrawl
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - BULL_AUTH_KEY
    - NUQ_POSTGRES_PASSWORD
    - RABBITMQ_PASSWORD
    - REDIS_PASSWORD
    - SELF_HOSTED_WEBHOOK_HMAC_SECRET
    - TEST_API_KEY
