---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl-secrets
  namespace: firecrawl
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: firecrawl-secret
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: firecrawl-secrets
