apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-staging
spec:
  acme:
    email: igou.david@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: igou.david@gmail.com
          apiKeySecretRef:
            name: dns-token
            key: dns-token
