apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
resources:
  - ../../../components/democratic-csi
  - democratic-csi-nfs-config-externalsecret.yaml
  - democratic-csi-iscsi-config-externalsecret.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
