apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - postgresql-externalsecret.yml
helmCharts:
- name: prometheus-postgres-exporter
  namespace: monitoring
  includeCRDs: false
  releaseName: monitoring
  version: 6.10.2
  repo: https://prometheus-community.github.io/helm-charts
  valuesInline:
    serviceMonitor:
      enabled: true
    config:
      datasource:
        host: pgsql.igou.systems
        user: postgres
        passwordSecret:
          name: postgresql
          key: password
