apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-iscsi-ssd-config
  namespace: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: democratic-csi-iscsi-ssd-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |-
          driver: freenas-iscsi
          instance_id:
          httpConnection:
            protocol: https
            host: {{ .truenas_host }}
            port: 443
            apiKey: {{ .truenas_api_key }}
            allowInsecure: false
            apiVersion: 2
          sshConnection:
            host: {{ .truenas_host }}
            port: 22
            username: {{ .truenas_user }}
            privateKey: |-{{ .truenas_ssh_key | b64dec | nindent 4}}
          zfs:
            cli:
              sudoEnabled: true
              paths:
                zfs: /sbin/zfs
                zpool: /sbin/zpool
                sudo: /bin/sudo
                chroot: /sbin/chroot
            datasetParentName: ssd_pool/k8s/vols
            detachedSnapshotsDatasetParentName: ssd_pool/k8sbak/vols
            zvolCompression:
            zvolDedup:
            zvolEnableReservation: false
            zvolBlocksize:
          iscsi:
            targetPortal: "{{ .truenas_host }}:3260"
            interface:
            namePrefix: csi-
            nameSuffix: "-cluster"
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup:
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: "SSD"
            extentAvailThreshold: 0
  dataFrom:
  - extract:
      key: truenas
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None