apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-nfs-ssd-config
  namespace: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: democratic-csi-nfs-ssd-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |-
          driver: freenas-nfs
          instance_id:
          httpConnection:
            protocol: https
            host: {{ .truenas_host }}
            port: 443
            apiKey: {{ .truenas_api_key }}
            allowInsecure: false
            apiVersion: 2
          sshConnection:
            host: {{ .truenas_host }}
            port: 22
            username: {{ .truenas_user }}
            privateKey: |-{{ .truenas_ssh_key | b64dec | nindent 4}}
          zfs:
            cli:
              sudoEnabled: true
              paths:
                zfs: /sbin/zfs
                zpool: /sbin/zpool
                sudo: /bin/sudo
                chroot: /sbin/chroot
            datasetParentName: ssd_pool/k8s/vols
            detachedSnapshotsDatasetParentName: ssd_pool/k8sbak/vols
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareHost: truenas.igou.systems
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks: []
            shareMaprootUser: root
            shareMaprootGroup: wheel
            shareMapallUser: ""
            shareMapallGroup: ""
  dataFrom:
  - extract:
      key: truenas
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None