apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 24h
  dataFrom:
  - extract:
      key: tailscale-oauth
