{
 "title": "Logging / Collection",
 "tags": [ "logging" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Log collection rate (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(namespace, app_kubernetes_io_instance) (rate(vector_component_received_bytes_total{component_kind=\"source\", component_type!=\"internal_metrics\"}[5m]))",
       "legendFormat": "{{namespace}}/{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "Log send rate (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace, app_kubernetes_io_instance) (rate(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\"}[5m]))",
       "legendFormat": "{{namespace}}/{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "Total errors last 60m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "none" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(namespace, app_kubernetes_io_instance) (increase(vector_component_errors_total[1h]))",
       "legendFormat": "{{namespace}}/{{app_kubernetes_io_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Rate log bytes sent per output",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (app_kubernetes_io_instance, namespace, component_id, component_type)(irate(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\"}[5m]))",
       "legendFormat": "{{namespace}}/{{app_kubernetes_io_instance}} | Output: {{component_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Produced Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top producing containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "format": "bytes",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, round(rate(log_logged_bytes_total[5m])))",
       "legendFormat": "{{exported_namespace}}/{{podname}}/{{containername}}"
      }
     ]
    },
    {
     "title": "Top producing containers in last 24 hours",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(increase(log_logged_bytes_total[24h])) by (exported_namespace,  podname, containername))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Collected Logs",
   "type": "row",
   "panels": [
    {
     "title": "Top collected containers - Bytes/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, round(rate(vector_component_received_event_bytes_total{component_type = \"kubernetes_logs\"}[5m])))",
       "legendFormat": "{{pod_namespace}}/{{pod_name}}/{{container_name}}"
      }
     ]
    },
    {
     "title": "Top collected containers in last 24 hours",
     "type": "table",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (container_name, pod_name, pod_namespace) (increase(vector_component_received_event_bytes_total{component_type=\"kubernetes_logs\"}[24h]))) / 1024 / 1024"
      }
     ]
    }
   ]
  },
  {
   "title": "Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by(node,namespace,pod)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container='collector'})",
       "legendFormat": "{{node}}/{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(node,namespace,pod)(node_namespace_pod_container:container_memory_rss{container=\"collector\"})",
       "legendFormat": "{{node}}/{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Running containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kubelet_running_containers{container_state=\"running\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Open files for container logs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(hostname,namespace,pod)(vector_open_files{component_kind=\"source\", component_type=\"kubernetes_logs\"})",
       "legendFormat": "{{hostname}}/{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "File Descriptors In Use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Sum" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace, forwarder)(label_replace(container_file_descriptors{container=~'collector'}, 'forwarder', '$1', 'pod', '(.*).{6}'))",
       "legendFormat": "{{namespace}}/{{forwarder}}"
      }
     ]
    },
    {
     "title": "Collector buffer consuming bytes disk space on node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "format": "bytes",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(hostname, component_kind, namespace, app_kubernetes_io_instance)(vector_buffer_byte_size{component_kind='sink', buffer_type='disk'})",
       "legendFormat": "{{hostname}}/{{namespace}}/{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "Collector buffer consuming % disk space on node",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(sum by(hostname) (vector_buffer_byte_size{component_kind='sink', buffer_type='disk'}), 'instance', '$1', 'hostname', '(.*)') / on(instance) group_left() sum by(instance) (node_filesystem_size_bytes{mountpoint='/var'})"
      }
     ]
    }
   ]
  }
 ]
}