apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - external-secrets-namespace.yaml
helmCharts:
- name: external-secrets
  includeCRDs: true
  releaseName: external-secrets
  namespace: external-secrets
  version: 2.6.0
  repo: https://charts.external-secrets.io
  valuesInline:
    replicaCount: 1

    installCRDs: true

    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createClusterGenerator: true
      createClusterPushSecret: true
      createPushSecret: true
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
      conversion:
        enabled: false

    leaderElect: false

    bitwarden-sdk-server:
      enabled: false

    serviceMonitor:
      enabled: false
