namespace: cert-manager
resources:
  - dns-token-externalsecret.yaml
  - letsencrypt-prod-clusterissuer.yaml
  - letsencrypt-staging-clusterissuer.yaml
  - cert-manager-namespace.yml
helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  version: v1.17.1
  repo: https://charts.jetstack.io
  valuesInline:
    crds:
      enabled: true
    global:
      # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
      logLevel: 6
      leaderElection:
        # Override the namespace used to store the ConfigMap for leader election
        namespace: "cert-manager"

        # The duration that non-leader candidates will wait after observing a
        # leadership renewal until attempting to acquire leadership of a led but
        # unrenewed leader slot. This is effectively the maximum duration that a
        # leader can be stopped before it is replaced by another candidate.
        # leaseDuration: 60s

        # The interval between attempts by the acting master to renew a leadership
        # slot before it stops leading. This must be less than or equal to the
        # lease duration.
        # renewDeadline: 40s

        # The duration the clients should wait between attempting acquisition and
        # renewal of a leadership.
        # retryPeriod: 15s
    extraArgs:
      - --default-issuer-name=letsencrypt-prod
      - --default-issuer-kind=ClusterIssuer
      - --cluster-resource-namespace=cert-manager
      - --enable-certificate-owner-ref=true
      - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
      - --dns01-recursive-nameservers-only
    replicaCount: 1
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring
        targetPort: 9402
        path: /metrics
        interval: 60s
        scrapeTimeout: 30s
        labels: {}
        honorLabels: false