name: logging
apiVersion: v2
version: 1.0.0
dependencies:
  - name: loki
    version: 6.32.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.17.0
    repository: https://grafana.github.io/helm-charts
