apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  generators:
    - git:
        directories:
          - path: config/internal/*
          - path: config/internal/monitoring/*
          # - exclude: true
          #   path: config/internal/live/base-config
        repoURL: 'https://github.com/igou-io/igou-kubernetes.git'
        revision: HEAD
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      name: '{{ path.basename }}'
    spec:
      destination:
        namespace: default
        server: 'https://kubernetes.default.svc'
      project: default
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
      source:
        path: '{{ path }}'
        repoURL: 'https://github.com/igou-io/igou-kubernetes.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true