apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj/argo-cd.git/manifests/cluster-install/?ref=v2.14.20
  - igou-kubernetes-repo-secret.yml
  - argocd-ingress.yml
  - argocd-notifications-secret-externalsecret.yml
  - cluster-applicationset.yml
patches:
- path: https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml
- path: argocd-notifications-cm-configmap.yml
- path: argocd-cm-configmap.yml