---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-rk8s
  target:
    name: searxng-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: searxng-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
