namespace: ingress
resources:
  - igou-wildcard-certificate.yml
helmCharts:
- name: ingress-nginx
  namespace: ingress
  includeCRDs: true
  releaseName: ingress-nginx
  version: 4.12.0
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    #namespaceOverride: ingress
    controller:
      admissionWebhooks:
        enabled: false
      extraArgs:
        default-ssl-certificate: "ingress/igou-wildcard"
      kind: DaemonSet
      hostNetwork: false
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      service:
        enabled: true
      publishService:
        enabled: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true